// Builds sfx/pack.mp3: every short sound effect in one file, and src/sfx-pack.js: where each one is in it.
// The game fetches the pack once and plays each sound from its stretch (src/audio-engine.js).
//
//   cd tools && npm i && node pack-sfx.mjs
//
// Run it again after adding or changing a sound in PACK below (or an item drop, or a soundboard pick).
// Until then the engine just loads that sound's own file, so nothing breaks in the meantime.
// Decodes with ffmpeg if it's installed, else macOS's afconvert.
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execFileSync } from 'node:child_process';
import { Mp3Encoder } from '@breezystack/lamejs';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const RATE = 48000, KBPS = 128;
const GAP = 0.12;   // silence between sounds (seconds), so one never bleeds into the next
const MARK = 0.05;  // where the alignment click sits (see the engine's loadPack)

// The short sounds. Long ones (music, ambience, the nuke's sirens and roars) stream from their own files.
const PACK = [
    'FOOT3.mp3', 'footsteps-on-wood-floor-14735.wav', 'whu6.wav', 'run.wav', 'key.wav', 'tada.wav', 'squeak-duck.mp3',
    'cartoonslip.mp3', 'beep2.mp3', 'Kerplunk.wav', 'slap.mp3', 'villager.mp3', 'STOMP2.ogg', 'crash.wav',
    'Cash_Register_Open_01.wav', 'attentioncustomers.wav', '20200624_Cartoon Splat sound effect.wav',
    'ES_Notification, Attention, Text, Reveal, Positive 01 - Epidemic Sound - 4178-4632.wav',
    'sfx/cart_drop.wav', 'sfx/cart_roll.wav', 'sfx/ui_hover.wav', 'sfx/ui_click.wav', 'sfx/text_chime.wav', 'sfx/phone_ring.wav',
    'sfx/fnaf_jumpscare.wav', 'sfx/thermostat_ice_crack.wav', 'sfx/freezer_door_creak.wav', 'sfx/freezer_seal_pop.wav',
    'sfx/freezer_door_slam.wav', 'sfx/shelf_replace.wav', 'sfx/yoink.wav', 'sfx/entrance_beep.wav', 'sfx/glass_break.wav',
    'sfx/tweaker_grunt.wav', 'sfx/money_pickup.wav', 'sfx/target_pop.wav', 'sfx/eat_sample.wav', 'sfx/toilet_flush.wav',
    'sfx/pee_stream.wav', 'sfx/car_crank.wav', 'sfx/car_start.wav', 'sfx/car_drive.wav',
    'sfx/nuke_alert.wav', 'sfx/nuke_whistle.wav', 'sfx/nuke_shockwave.wav', 'BABYCRY.mp3.opus',
];
// the soundboard picks (src/sound-picks.js) and every item's drop
const picks = fs.readFileSync(path.join(ROOT, 'src/sound-picks.js'), 'utf8').match(/SOUND_PICKS = (\{[\s\S]*\});/);
for (const v of Object.values(picks ? JSON.parse(picks[1]) : {})) if (!PACK.includes(v.src)) PACK.push(v.src);
for (const f of fs.readdirSync(path.join(ROOT, 'sfx/drops')).sort()) if (/\.(mp3|wav|ogg)$/.test(f) && !PACK.includes('sfx/drops/' + f)) PACK.push('sfx/drops/' + f);

const hasFfmpeg = (() => { try { execFileSync('ffmpeg', ['-version'], { stdio: 'ignore' }); return true; } catch (_) { return false; } })();
const tmp = path.join(os.tmpdir(), 'pack-sfx.f32');
// a file as mono float samples at RATE, read the way a browser reads it (its header as written)
function decode(file) {
    if (hasFfmpeg) execFileSync('ffmpeg', ['-v', 'error', '-y', '-i', file, '-ac', '1', '-ar', String(RATE), '-f', 'f32le', tmp]);
    else execFileSync('afconvert', ['-f', 'WAVE', '-d', `LEF32@${RATE}`, '-c', '1', file, tmp + '.wav']);
    const b = fs.readFileSync(hasFfmpeg ? tmp : tmp + '.wav');
    let data = b;
    if (!hasFfmpeg) { // find the WAV's data chunk
        let o = 12; while (o < b.length - 8 && b.toString('ascii', o, o + 4) !== 'data') o += 8 + b.readUInt32LE(o + 4);
        data = b.subarray(o + 8, o + 8 + b.readUInt32LE(o + 4));
    }
    return new Float32Array(data.buffer.slice(data.byteOffset, data.byteOffset + (data.length & ~3)));
}

const parts = [], sounds = {};
let at = 0;
const push = (x) => { parts.push(x); at += x.length; };
const silence = (sec) => push(new Float32Array(Math.round(sec * RATE)));
silence(MARK);
const click = new Float32Array(Math.round(0.002 * RATE)).fill(0.9); push(click);
silence(0.2);
for (const rel of PACK) {
    const file = path.join(ROOT, rel);
    if (!fs.existsSync(file)) { console.warn('missing, skipped:', rel); continue; }
    const x = decode(file);
    sounds[rel] = [+(at / RATE).toFixed(5), +(x.length / RATE).toFixed(5)];
    push(x); silence(GAP);
}
const all = new Float32Array(at); let o = 0; for (const p of parts) { all.set(p, o); o += p.length; }

const pcm = new Int16Array(all.length);
for (let i = 0; i < all.length; i++) pcm[i] = Math.round(Math.max(-1, Math.min(1, all[i])) * 32767);
const enc = new Mp3Encoder(1, RATE, KBPS), mp3 = [];
for (let i = 0; i < pcm.length; i += 1152) { const m = enc.encodeBuffer(pcm.subarray(i, i + 1152)); if (m.length) mp3.push(Buffer.from(m)); }
mp3.push(Buffer.from(enc.flush()));
const out = Buffer.concat(mp3);
fs.writeFileSync(path.join(ROOT, 'sfx/pack.mp3'), out);
fs.writeFileSync(path.join(ROOT, 'src/sfx-pack.js'), `// Generated by tools/pack-sfx.mjs. Do not edit by hand.
// sfx/pack.mp3 holds these sounds back to back: file -> [start, duration] in seconds. mark: where the
// alignment click is (the engine finds it to correct for decoder padding).
export const SFX_PACK = ${JSON.stringify({ src: 'sfx/pack.mp3', mark: MARK, sounds }, null, 1)};
`);
console.log(`sfx/pack.mp3: ${Object.keys(sounds).length} sounds, ${(all.length / RATE).toFixed(1)} s, ${(out.length / 1048576).toFixed(2)} MB`);
