// Generated by tools/pack-sfx.mjs (cd tools && npm i && node pack-sfx.mjs).
// sfx/pack.mp3 holds these sounds back to back: file -> [start, duration] in seconds. mark: where the
// alignment click is (the engine finds it to correct for decoder padding).
//
// Adding a sound: nothing to do here. A file that isn't listed loads on its own, as it always did.
// CHANGING a sound that's listed (new audio, same file name): the pack still has the old audio, so
// either run the tool again, or delete that file's line below and it loads its own file again.
export const SFX_PACK = {
 "src": "sfx/pack.mp3",
 "mark": 0.05,
 "sounds": {
  "FOOT3.mp3": [
   0.252,
   0.15673
  ],
  "footsteps-on-wood-floor-14735.wav": [
   0.52873,
   3.21092
  ],
  "whu6.wav": [
   3.85965,
   0.14
  ],
  "run.wav": [
   4.11965,
   0.28325
  ],
  "key.wav": [
   4.5229,
   0.19912
  ],
  "tada.wav": [
   4.84202,
   1.25894
  ],
  "squeak-duck.mp3": [
   6.22096,
   1.7415
  ],
  "cartoonslip.mp3": [
   8.08246,
   0.19827
  ],
  "beep2.mp3": [
   8.40073,
   0.17415
  ],
  "Kerplunk.wav": [
   8.69487,
   0.17913
  ],
  "slap.mp3": [
   8.994,
   0.63319
  ],
  "villager.mp3": [
   9.74719,
   0.864
  ],
  "STOMP2.ogg": [
   10.73119,
   0.52
  ],
  "crash.wav": [
   11.37119,
   2.61244
  ],
  "Cash_Register_Open_01.wav": [
   14.10362,
   1.81585
  ],
  "attentioncustomers.wav": [
   16.03948,
   7.78413
  ],
  "20200624_Cartoon Splat sound effect.wav": [
   23.9436,
   0.89398
  ],
  "ES_Notification, Attention, Text, Reveal, Positive 01 - Epidemic Sound - 4178-4632.wav": [
   24.95758,
   0.454
  ],
  "sfx/cart_drop.wav": [
   25.53158,
   1
  ],
  "sfx/cart_roll.wav": [
   26.65158,
   10
  ],
  "sfx/ui_hover.wav": [
   36.77158,
   0.96
  ],
  "sfx/ui_click.wav": [
   37.85158,
   1.2
  ],
  "sfx/text_chime.wav": [
   39.17158,
   2
  ],
  "sfx/phone_ring.wav": [
   41.29158,
   6
  ],
  "sfx/fnaf_jumpscare.wav": [
   47.41158,
   4.96
  ],
  "sfx/thermostat_ice_crack.wav": [
   52.49158,
   3.67873
  ],
  "sfx/freezer_door_creak.wav": [
   56.29031,
   4.96
  ],
  "sfx/freezer_seal_pop.wav": [
   61.37031,
   2.4
  ],
  "sfx/freezer_door_slam.wav": [
   63.89031,
   2.96
  ],
  "sfx/shelf_replace.wav": [
   66.97031,
   4.96
  ],
  "sfx/yoink.wav": [
   72.05031,
   2
  ],
  "sfx/entrance_beep.wav": [
   74.17031,
   2.4
  ],
  "sfx/glass_break.wav": [
   76.69031,
   2.96
  ],
  "sfx/tweaker_grunt.wav": [
   79.77031,
   1.6
  ],
  "sfx/money_pickup.wav": [
   81.49031,
   1.6
  ],
  "sfx/target_pop.wav": [
   83.21031,
   2
  ],
  "sfx/eat_sample.wav": [
   85.33031,
   2.93904
  ],
  "sfx/toilet_flush.wav": [
   88.38935,
   4.96
  ],
  "sfx/pee_stream.wav": [
   93.46935,
   8
  ],
  "sfx/car_crank.wav": [
   101.58935,
   4.5
  ],
  "sfx/car_start.wav": [
   106.20935,
   4.96
  ],
  "sfx/car_drive.wav": [
   111.28935,
   6
  ],
  "sfx/nuke_alert.wav": [
   117.40935,
   6
  ],
  "sfx/nuke_whistle.wav": [
   123.52935,
   8
  ],
  "sfx/nuke_shockwave.wav": [
   131.64935,
   8
  ],
  "BABYCRY.mp3.opus": [
   139.76935,
   10.0335
  ],
  "sfx/door_open.mp3": [
   149.92285,
   1.944
  ],
  "sfx/door_close.mp3": [
   151.98685,
   1.896
  ],
  "sfx/cart_roll_empty.wav": [
   154.00285,
   6
  ],
  "sfx/cart_roll_full.wav": [
   160.12285,
   5
  ],
  "sfx/cart_roll_rough.wav": [
   165.24285,
   4
  ],
  "sfx/cart_stuck_squeak.wav": [
   169.36285,
   4
  ],
  "sfx/cart_handle.mp3": [
   173.48285,
   0.552
  ],
  "sfx/steps_store.wav": [
   174.15485,
   5.76
  ],
  "sfx/steps_lot.wav": [
   180.03485,
   5.76
  ],
  "sfx/npc_cart_roll.wav": [
   185.91485,
   6
  ],
  "sfx/drops/apples.mp3": [
   192.03485,
   0.816
  ],
  "sfx/drops/bananas.mp3": [
   192.97085,
   0.72
  ],
  "sfx/drops/batteries.mp3": [
   193.81085,
   0.36
  ],
  "sfx/drops/bread.mp3": [
   194.29085,
   0.216
  ],
  "sfx/drops/canned-goods.mp3": [
   194.62685,
   0.576
  ],
  "sfx/drops/cereal.mp3": [
   195.32285,
   1.032
  ],
  "sfx/drops/cheese.mp3": [
   196.47485,
   1.032
  ],
  "sfx/drops/chewing-gum.mp3": [
   197.62685,
   0.984
  ],
  "sfx/drops/chicken.mp3": [
   198.73085,
   0.408
  ],
  "sfx/drops/chocolate-bars.mp3": [
   199.25885,
   0.36
  ],
  "sfx/drops/cleaning-supplies.mp3": [
   199.73885,
   0.456
  ],
  "sfx/drops/coffee.mp3": [
   200.31485,
   0.432
  ],
  "sfx/drops/cooking-oil.mp3": [
   200.86685,
   0.744
  ],
  "sfx/drops/dog-food.mp3": [
   201.73085,
   0.648
  ],
  "sfx/drops/eggs.mp3": [
   202.49885,
   0.864
  ],
  "sfx/drops/flowers.mp3": [
   203.48285,
   0.936
  ],
  "sfx/drops/grapes.mp3": [
   204.53885,
   0.456
  ],
  "sfx/drops/ice-cream.mp3": [
   205.11485,
   0.408
  ],
  "sfx/drops/ketchup.mp3": [
   205.64285,
   0.624
  ],
  "sfx/drops/lettuce.mp3": [
   206.38685,
   0.84
  ],
  "sfx/drops/milk.mp3": [
   207.34685,
   0.456
  ],
  "sfx/drops/mustard.mp3": [
   207.92285,
   0.864
  ],
  "sfx/drops/orange-juice.mp3": [
   208.90685,
   0.864
  ],
  "sfx/drops/pants.mp3": [
   209.89085,
   0.216
  ],
  "sfx/drops/pasta-sauce.mp3": [
   210.22685,
   0.792
  ],
  "sfx/drops/pasta.mp3": [
   211.13885,
   1.008
  ],
  "sfx/drops/peanut-butter.mp3": [
   212.26685,
   0.36
  ],
  "sfx/drops/pizza.mp3": [
   212.74685,
   0.552
  ],
  "sfx/drops/potatoes.mp3": [
   213.41885,
   0.624
  ],
  "sfx/drops/shampoo.mp3": [
   214.16285,
   1.008
  ],
  "sfx/drops/soda.mp3": [
   215.29085,
   0.912
  ],
  "sfx/drops/steak.mp3": [
   216.32285,
   0.816
  ],
  "sfx/drops/sugar.mp3": [
   217.25885,
   0.864
  ],
  "sfx/drops/toilet-paper.mp3": [
   218.24285,
   0.912
  ],
  "sfx/drops/towels.mp3": [
   219.27485,
   0.456
  ],
  "sfx/drops/toys.mp3": [
   219.85085,
   0.744
  ],
  "sfx/drops/water-bottles.mp3": [
   220.71485,
   0.864
  ],
  "sfx/drops/watermelon.mp3": [
   221.69885,
   0.576
  ],
  "sfx/cart_crash.mp3": [
   222.39485,
   1.2
  ]
 }
};
