// Generated by shopping-sfx/export-picks.mjs from the soundboard's picks. Do not edit by hand.
// job -> {src: the file in sfx/, take: the soundboard take it came from, arriveAt: for a door, seconds into
// the file when the door is fully open/shut (the slide ends there)}
export const SOUND_PICKS = {
 "door-open": {
  "src": "sfx/door_open.mp3",
  "take": "door-open/el-door-open-a",
  "arriveAt": 1.657,
  "arriveSet": true
 },
 "door-close": {
  "src": "sfx/door_close.mp3",
  "take": "door-close/el-door-close-b",
  "arriveAt": 1.32,
  "arriveSet": false
 },
 "cart-roll-empty": {
  "src": "sfx/cart_roll_empty.wav",
  "take": "roll-indoor/el-roll-indoor-rattle"
 },
 "cart-roll-full": {
  "src": "sfx/cart_roll_full.wav",
  "take": "roll-indoor/now-cart_roll-fixed"
 },
 "cart-roll-rough": {
  "src": "sfx/cart_roll_rough.wav",
  "take": "roll-outdoor/es-cart-push-concrete-pushing-perspective-1",
  "semitones": -12
 },
 "cart-stuck": {
  "src": "sfx/cart_stuck_squeak.wav",
  "take": "stuck-wheel/es-squeaky-wheels-movement-accelerating-3"
 },
 "cart-handle": {
  "src": "sfx/cart_handle.mp3",
  "take": "handle/el-grab"
 },
 "steps-store": {
  "src": "sfx/steps_store.wav",
  "take": "steps-store/es-footsteps-human-tiles-sneakers-walking-speed",
  "lowpassHz": 300,
  "steps": [
   [
    0,
    0.4
   ],
   [
    0.48,
    0.88
   ],
   [
    0.96,
    1.36
   ],
   [
    1.44,
    1.84
   ],
   [
    1.92,
    2.32
   ],
   [
    2.4,
    2.8
   ],
   [
    2.88,
    3.28
   ],
   [
    3.36,
    3.76
   ],
   [
    3.84,
    4.24
   ],
   [
    4.32,
    4.72
   ],
   [
    4.8,
    5.2
   ],
   [
    5.28,
    5.68
   ]
  ]
 },
 "steps-lot": {
  "src": "sfx/steps_lot.wav",
  "take": "steps-lot/es-footsteps-human-shoes-asphalt-walk",
  "lowpassHz": 300,
  "steps": [
   [
    0,
    0.4
   ],
   [
    0.48,
    0.88
   ],
   [
    0.96,
    1.36
   ],
   [
    1.44,
    1.84
   ],
   [
    1.92,
    2.32
   ],
   [
    2.4,
    2.8
   ],
   [
    2.88,
    3.28
   ],
   [
    3.36,
    3.76
   ],
   [
    3.84,
    4.24
   ],
   [
    4.32,
    4.72
   ],
   [
    4.8,
    5.2
   ],
   [
    5.28,
    5.68
   ]
  ]
 },
 "npc-cart-roll": {
  "src": "sfx/npc_cart_roll.wav",
  "take": "roll-indoor/el-roll-indoor-rattle"
 },
 "drop-apples": {
  "src": "sfx/drops/apples.mp3",
  "take": "item-bag/el-item-bag"
 },
 "drop-bananas": {
  "src": "sfx/drops/bananas.mp3",
  "take": "drop-bananas/el-drop-bananas-v2"
 },
 "drop-batteries": {
  "src": "sfx/drops/batteries.mp3",
  "take": "drop-batteries/el-drop-batteries-plain",
  "auto": true
 },
 "drop-bread": {
  "src": "sfx/drops/bread.mp3",
  "take": "item-bag/es-plastic-bag-items-inside-drop-table",
  "lowpassHz": 1986
 },
 "drop-canned-goods": {
  "src": "sfx/drops/canned-goods.mp3",
  "take": "drop-canned-goods/el-drop-canned-goods-plain",
  "auto": true
 },
 "drop-cereal": {
  "src": "sfx/drops/cereal.mp3",
  "take": "drop-cereal/el-drop-cereal"
 },
 "drop-cheese": {
  "src": "sfx/drops/cheese.mp3",
  "take": "drop-cheese/el-drop-cheese-plain",
  "auto": true
 },
 "drop-chewing-gum": {
  "src": "sfx/drops/chewing-gum.mp3",
  "take": "drop-chewing-gum/el-drop-chewing-gum-plain",
  "auto": true
 },
 "drop-chicken": {
  "src": "sfx/drops/chicken.mp3",
  "take": "drop-chicken/el-drop-chicken-plain",
  "auto": true
 },
 "drop-chocolate-bars": {
  "src": "sfx/drops/chocolate-bars.mp3",
  "take": "drop-chocolate-bars/el-drop-chocolate-bars-plain",
  "auto": true
 },
 "drop-cleaning-supplies": {
  "src": "sfx/drops/cleaning-supplies.mp3",
  "take": "drop-cleaning-supplies/el-drop-cleaning-supplies-plain",
  "auto": true
 },
 "drop-coffee": {
  "src": "sfx/drops/coffee.mp3",
  "take": "drop-coffee/el-drop-coffee-plain",
  "auto": true
 },
 "drop-cooking-oil": {
  "src": "sfx/drops/cooking-oil.mp3",
  "take": "drop-cooking-oil/el-drop-cooking-oil-plain",
  "auto": true
 },
 "drop-dog-food": {
  "src": "sfx/drops/dog-food.mp3",
  "take": "drop-dog-food/el-drop-dog-food-plain",
  "auto": true
 },
 "drop-eggs": {
  "src": "sfx/drops/eggs.mp3",
  "take": "drop-eggs/el-drop-eggs"
 },
 "drop-flowers": {
  "src": "sfx/drops/flowers.mp3",
  "take": "drop-flowers/el-drop-flowers-plain",
  "auto": true
 },
 "drop-grapes": {
  "src": "sfx/drops/grapes.mp3",
  "take": "drop-grapes/el-drop-grapes-plain",
  "auto": true
 },
 "drop-ice-cream": {
  "src": "sfx/drops/ice-cream.mp3",
  "take": "drop-ice-cream/el-drop-ice-cream-plain",
  "auto": true
 },
 "drop-ketchup": {
  "src": "sfx/drops/ketchup.mp3",
  "take": "drop-ketchup/el-drop-ketchup-plain",
  "auto": true
 },
 "drop-lettuce": {
  "src": "sfx/drops/lettuce.mp3",
  "take": "drop-lettuce/el-drop-lettuce-plain",
  "auto": true
 },
 "drop-milk": {
  "src": "sfx/drops/milk.mp3",
  "take": "drop-milk/el-drop-milk"
 },
 "drop-mustard": {
  "src": "sfx/drops/mustard.mp3",
  "take": "drop-mustard/el-drop-mustard-plain",
  "auto": true
 },
 "drop-orange-juice": {
  "src": "sfx/drops/orange-juice.mp3",
  "take": "drop-orange-juice/el-drop-orange-juice-plain",
  "auto": true
 },
 "drop-pants": {
  "src": "sfx/drops/pants.mp3",
  "take": "drop-pants/el-drop-pants-plain",
  "auto": true
 },
 "drop-pasta-sauce": {
  "src": "sfx/drops/pasta-sauce.mp3",
  "take": "drop-pasta-sauce/el-drop-pasta-sauce-plain",
  "auto": true
 },
 "drop-pasta": {
  "src": "sfx/drops/pasta.mp3",
  "take": "drop-pasta/el-drop-pasta-plain",
  "auto": true
 },
 "drop-peanut-butter": {
  "src": "sfx/drops/peanut-butter.mp3",
  "take": "drop-peanut-butter/el-drop-peanut-butter-plain",
  "auto": true
 },
 "drop-pizza": {
  "src": "sfx/drops/pizza.mp3",
  "take": "drop-pizza/el-drop-pizza-plain",
  "auto": true
 },
 "drop-potatoes": {
  "src": "sfx/drops/potatoes.mp3",
  "take": "drop-potatoes/el-drop-potatoes-plain",
  "auto": true
 },
 "drop-shampoo": {
  "src": "sfx/drops/shampoo.mp3",
  "take": "drop-shampoo/el-drop-shampoo-plain",
  "auto": true
 },
 "drop-soda": {
  "src": "sfx/drops/soda.mp3",
  "take": "drop-soda/el-drop-soda-plain",
  "auto": true
 },
 "drop-steak": {
  "src": "sfx/drops/steak.mp3",
  "take": "drop-steak/el-drop-steak-plain",
  "auto": true
 },
 "drop-sugar": {
  "src": "sfx/drops/sugar.mp3",
  "take": "drop-sugar/el-drop-sugar-plain",
  "auto": true
 },
 "drop-toilet-paper": {
  "src": "sfx/drops/toilet-paper.mp3",
  "take": "drop-toilet-paper/el-drop-toilet-paper-plain",
  "auto": true
 },
 "drop-towels": {
  "src": "sfx/drops/towels.mp3",
  "take": "drop-towels/el-drop-towels-plain",
  "auto": true
 },
 "drop-toys": {
  "src": "sfx/drops/toys.mp3",
  "take": "drop-toys/el-drop-toys-plain",
  "auto": true
 },
 "drop-water-bottles": {
  "src": "sfx/drops/water-bottles.mp3",
  "take": "drop-water-bottles/el-drop-water-bottles-plain",
  "auto": true
 },
 "drop-watermelon": {
  "src": "sfx/drops/watermelon.mp3",
  "take": "drop-watermelon/el-drop-watermelon-plain",
  "auto": true
 }
};
