// Generated by shopping-sfx/export-picks.mjs from the soundboard's picks. Do not edit by hand.
// job -> {src: the file in sfx/, take: the soundboard take it came from, arriveAt: for a door, seconds into
// the file when the door is fully open/shut (the slide ends there)}
export const SOUND_PICKS = {
 "door-open": {
  "src": "sfx/door_open.mp3",
  "take": "door-open/el-door-open-a",
  "arriveAt": 1.657,
  "arriveSet": true
 },
 "door-close": {
  "src": "sfx/door_close.mp3",
  "take": "door-close/el-door-close-b",
  "arriveAt": 1.32,
  "arriveSet": false
 }
};
