// Generated by shopping-sfx/export-picks.mjs from the soundboard's picks. Do not edit by hand.
// job -> {src: the file in sfx/, take: the soundboard take it came from, arriveAt: for a door, seconds into
// the file when the door is fully open/shut (the slide ends there)}
export const SOUND_PICKS = {
 "door-open": {
  "src": "sfx/door_open.mp3",
  "take": "door-open/el-door-open-a",
  "arriveAt": 1.657,
  "arriveSet": true
 },
 "door-close": {
  "src": "sfx/door_close.mp3",
  "take": "door-close/el-door-close-b",
  "arriveAt": 1.32,
  "arriveSet": false
 },
 "cart-roll-empty": {
  "src": "sfx/cart_roll_empty.wav",
  "take": "roll-indoor/el-roll-indoor-rattle"
 },
 "cart-roll-full": {
  "src": "sfx/cart_roll_full.wav",
  "take": "roll-indoor/now-cart_roll-fixed"
 },
 "cart-roll-rough": {
  "src": "sfx/cart_roll_rough.wav",
  "take": "roll-outdoor/es-cart-push-concrete-pushing-perspective-1",
  "semitones": -12
 },
 "cart-stuck": {
  "src": "sfx/cart_stuck_squeak.wav",
  "take": "stuck-wheel/es-squeaky-wheels-movement-accelerating-3"
 },
 "cart-handle": {
  "src": "sfx/cart_handle.mp3",
  "take": "handle/el-grab"
 },
 "steps-store": {
  "src": "sfx/steps_store.wav",
  "take": "steps-store/es-footsteps-human-tiles-sneakers-walking-speed",
  "lowpassHz": 300,
  "steps": [
   [
    0,
    0.4
   ],
   [
    0.48,
    0.88
   ],
   [
    0.96,
    1.36
   ],
   [
    1.44,
    1.84
   ],
   [
    1.92,
    2.32
   ],
   [
    2.4,
    2.8
   ],
   [
    2.88,
    3.28
   ],
   [
    3.36,
    3.76
   ],
   [
    3.84,
    4.24
   ],
   [
    4.32,
    4.72
   ],
   [
    4.8,
    5.2
   ],
   [
    5.28,
    5.68
   ]
  ]
 },
 "steps-lot": {
  "src": "sfx/steps_lot.wav",
  "take": "steps-lot/es-footsteps-human-shoes-asphalt-walk",
  "lowpassHz": 300,
  "steps": [
   [
    0,
    0.4
   ],
   [
    0.48,
    0.88
   ],
   [
    0.96,
    1.36
   ],
   [
    1.44,
    1.84
   ],
   [
    1.92,
    2.32
   ],
   [
    2.4,
    2.8
   ],
   [
    2.88,
    3.28
   ],
   [
    3.36,
    3.76
   ],
   [
    3.84,
    4.24
   ],
   [
    4.32,
    4.72
   ],
   [
    4.8,
    5.2
   ],
   [
    5.28,
    5.68
   ]
  ]
 }
};
